sudo: false
env:
- PATH="$HOME/avr-gcc/bin:$PATH"
before_script:
- curl -L -O https://github.com/BrewTroller/toolchain-builder/releases/download/v5.4.0/avr-gcc-5.4.0-linux.tar.xz
  && tar xf avr-gcc*.tar.xz && mv avr-gcc $HOME/ && rm -rf avr-gcc*.tar.xz && cd $TRAVIS_BUILD_DIR
  && chmod +x build-all-test.sh
script:
- ./build-all-test.sh
notifications:
  slack:
    secure: iEre5TG5JhLfDHkqi3SpnePCoP2NGTdiVGN5O5/Iqn465C1H3ngsVHVXyBm015Pnr7LhN+lKFjHmgeVvzKy3v7JhZvwD5of2blFzk4l9kHerG2noEMQlbgJDnFpYvLHgu1M2p3s/A77PXTkqpNhNggNcWb+cyLYeqisXrWzzLvou+ofzImTNvydobi348Q4H3MeK45TTskuddDjo02uuyNxET+fac0v45i0GRk0no/vlFC8+1cHqOoZUuj9WEi1f89If1WXQSzp6kLtF6CnOAYXlqQyTIvjVlRFqmMrxBeeW86QqTf1Ab0eQ2sjzjpJ3xvc8lff9r9Fs4Wu3Fi5uLSJ6pyizu2OyzVk+M3ZNVjDcQ7vrN23uyRwBaMXRezb+gjdOtfxeOqq9Tg4QVsA0jZKPnhUfDobThbbxHMCnazNqEtfvGv5iLE1afuVOl0TmpNxc3tmSHAxlVndgCdiLPq7yizQwiXQTTHXuincE7n4Z/NQIw2IrjvBMDev3afNdBmmIvDbTENre6VQwfI4N0jKObS1mF4Fzkx30nv4CRqO0GDnI+Ad+wf63NV+Bf3bC4nSNoid53KXpZW6qqljkBYr9S5VAxiHmtsIyiKwFb1ObICOcnexUUspSaHoydx4r92PtrrDBxPTjxm6D3tbha3BJrLzWGfEXOLBD0gsCvz8=
